name: PR Merge Workflow

on:
  pull_request:
    types: [closed]
    branches:
      - main

permissions:
  contents: write  # リポジトリへの書き込み権限を付与

jobs:
  increment-version:
    if: github.event.pull_request.merged == true
    uses: ./.github/workflows/increment-version.yml

  release:
    needs: increment-version
    if: github.event.pull_request.merged == true
    uses: ./.github/workflows/release.yml