name: PR Merge Workflow

on:
  pull_request:
    types: [closed]
    branches:
      - main

permissions:
  contents: write

jobs:
  increment-version:
    if: github.event.pull_request.merged == true
    uses: ./.github/workflows/increment-version.yml
    secrets:
      DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}

  release:
    needs: increment-version
    if: github.event.pull_request.merged == true
    uses: ./.github/workflows/release.yml
    with:
      checkout_ref: main
    secrets:
      DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
